version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      coatl-dev-actions:
        patterns:
          - "coatl-dev/actions/**"
      coatl-dev-workflows:
        patterns:
          - "coatl-dev/workflows/**"
    labels: ["dependencies"]
    commit-message:
      prefix: "ci"
      include: "scope"
