[tox]
requires =
    tox>=4.2
    virtualenv<20.22.0
env_list =
    tests
    typecheck

[testenv:tests]
description = run tests
base_python = python2.7
commands =
    python -m unittest discover --verbose

[testenv:typecheck]
description = run type check on code base
base_python = python3.12
skip_install = true
deps =
    mypy[python2] @ git+https://github.com/coatl-dev/mypy.git@v0.971
commands =
    mypy --install-types --non-interactive src

[testenv:stubgen]
description = generate stubs
base_python = python3.12
skip_install = true
deps =
    mypy[python2] @ git+https://github.com/coatl-dev/mypy.git@v0.971
commands =
    stubgen --export-less --output=stubs{/}stubs src

[docformatter]
close-quotes-on-newline = true
in-place = true
wrap-summaries = 72

[flake8]
arg-type-hints-in-docstring = False
arg-type-hints-in-signature = False
check-return-types = False
ignore = DOC202, E741, F821
max-complexity = 10
max-doc-length = 72
max-line-length = 120
style = google

[isort]
extra_standard_library = typing
profile = black
py_version = 27

[pydocstyle]
add_ignore = D101, D102, D104, D105, D106, D107, D205, D415
convention = google
