name: tox

on:
  workflow_call:

jobs:
  tox-package:
    uses: coatl-dev/workflows/.github/workflows/tox-docker.yml@92e51b14907b5aac1a8af1fcd9c2a1a5369dc47a # v7.0.32

  tox-stubs:
    uses: coatl-dev/workflows/.github/workflows/tox.yml@92e51b14907b5aac1a8af1fcd9c2a1a5369dc47a # v7.0.32
    with:
      python-versions: |
        3.9
        3.10
        3.11
        3.12
      working-directory: stubs
